### ISSUE TITLE
文章概要无法显示啊

### ISSUE THREAD

**Issue by xiaomingming** [sun11/hexo-theme-paperbox#1]
用了这个模板，为何博文都是全部展示呢？
怎么设置成只显示一部分文字啊？

**Comment by frontEnd-fucker** [comment]
```
这里写文章摘要
<!--more-->
这里写余下正文
```

主页只显示文章摘要，点解`阅读全文`才显示全文。

**Comment by frontEnd-fucker** [comment]
用`<!--more-->`分隔开即可

**Comment by xiaomingming** [comment]
pacman主题没有针对每篇文章进行的设置，却能够显示一部分。
不知道这个如何在全局中进行控制，而不用在写博客时就设置？

**Comment by sun11** [comment]
我觉得这不是普遍需求...每篇文章设置`<!--more-->`即可，要自动截取对文章内容可能不合适。
